#!/bin/bash

echo "🚀 Deploying updated worker to ndlovucavelle account..."
echo ""
echo "⚠️  IMPORTANT: This script requires authentication with the ndlovucavelle Cloudflare account"
echo ""
echo "Please follow these steps:"
echo "1. Run: wrangler login"
echo "2. Make sure you're logged into the ndlovucavelle account (Account ID: 002bd5c0e90ae753a387c60546cf6869)"
echo "3. Then run: wrangler deploy --config wrangler-ndlovucavelle.toml"
echo ""
echo "The worker has been updated with the following endpoints:"
echo "✅ /api/auth/creator/login"
echo "✅ /api/auth/investor/login"
echo "✅ /api/auth/production/login"
echo "✅ /api/auth/creator/register"
echo "✅ /api/auth/investor/register"
echo "✅ /api/auth/production/register"
echo "✅ /api/auth/creator/logout"
echo "✅ /api/auth/investor/logout"
echo "✅ /api/auth/production/logout"
echo "✅ /api/dashboard/creator"
echo "✅ /api/dashboard/investor"
echo "✅ /api/dashboard/production"
echo "✅ /api/pitches/my"
echo ""
echo "Demo accounts that will work:"
echo "📧 alex.creator@demo.com (password: Demo123)"
echo "📧 sarah.investor@demo.com (password: Demo123)"
echo "📧 stellar.production@demo.com (password: Demo123)"