version: '3.8'

services:
  backend:
    image: docker.io/denoland/deno:alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pitchey
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
    command: run --allow-all working-server.ts
    depends_on:
      - db
      - redis
    restart: unless-stopped

  frontend:
    image: docker.io/node:18-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8001
    command: sh -c "npm install && npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: docker.io/postgres:15-alpine
    environment:
      POSTGRES_DB: pitchey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: docker.io/redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
