# fly.toml app configuration file generated for pitchey-backend on 2025-09-21T21:35:34+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pitchey-backend'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile.backend"

[env]
  # Redis is optional - app will work without it
  # Set REDIS_URL as a secret: fly secrets set REDIS_URL="redis://..." --app pitchey-backend
  # For Upstash Redis: redis://password@fly-your-db.upstash.io
  # For self-hosted: redis://:password@redis-app.internal:6379

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
