version: '3.8'

services:
  # Local PostgreSQL for development
  postgres:
    image: docker.io/postgres:16-alpine
    environment:
      POSTGRES_USER: pitchey_dev
      POSTGRES_PASSWORD: localdev123
      POSTGRES_DB: pitchey_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d:Z  # :Z for SELinux
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pitchey_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Let Podman handle permissions automatically

  # Local Redis for caching
  redis:
    image: docker.io/redis:7-alpine
    ports:
      - "6380:6379"  # Using 6380 to avoid conflict with system Redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # MinIO for local R2 simulation
  minio:
    image: docker.io/minio/minio:latest
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # Adminer for database management
  adminer:
    image: docker.io/adminer:latest
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  minio_data:
    driver: local

# Podman-specific network configuration
networks:
  default:
    driver: bridge