#!/bin/bash

echo "=========================================="
echo "Cloudflare Cache Purge Instructions"
echo "=========================================="
echo ""
echo "The new deployment with correct API URL is ready:"
echo "✅ https://42466145.pitchey-5o8.pages.dev"
echo ""
echo "To make pitchey.pages.dev use this deployment:"
echo ""
echo "OPTION 1: Use Cloudflare Dashboard (Recommended)"
echo "-------------------------------------------------"
echo "1. Go to: https://dash.cloudflare.com"
echo "2. Select your account"
echo "3. Go to Workers & Pages → pitchey"
echo "4. Click on 'Deployments' tab"
echo "5. Find deployment '42466145' (should be at the top)"
echo "6. Click the three dots (...) → 'Promote to Production'"
echo "7. Then go to 'Settings' → 'Caching'"
echo "8. Click 'Purge Everything'"
echo ""
echo "OPTION 2: Use Wrangler CLI"
echo "---------------------------"
echo "wrangler pages deployment promote --project-name=pitchey --deployment-id=42466145"
echo ""
echo "OPTION 3: Force new deployment as production alias"
echo "---------------------------------------------------"
echo "wrangler pages deployment create --project-name=pitchey --production"
echo ""
echo "=========================================="
echo "VERIFICATION:"
echo "After purging, test with:"
echo "curl -s https://pitchey.pages.dev | grep -o 'pitchey-api[^\"]*workers.dev' | head -1"
echo "Should show: pitchey-api-prod.ndlovucavelle.workers.dev"
echo "=========================================="