#!/bin/bash

echo "🎬 Testing Genre Dropdown on Create Pitch Page"
echo "==============================================="

# Test if we can access the create pitch page
echo "📋 Testing access to Create Pitch page..."

# Check if we can load the page (should redirect to login)
response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5173/creator/pitch/new)

if [ "$response" = "200" ]; then
    echo "✅ Create Pitch page accessible at http://localhost:5173/creator/pitch/new"
else
    echo "⚠️  Create Pitch page returned status code: $response"
    echo "   This is expected as it requires authentication"
fi

echo ""
echo "🔍 Manual verification needed:"
echo "1. Open http://localhost:5173/creator/pitch/new in your browser"
echo "2. Login with demo creator account: alex.creator@demo.com / Demo123"
echo "3. Check the Genre dropdown should contain ALL these options:"
echo ""
echo "   • Abstract / Non-Narrative"
echo "   • Action"
echo "   • Action-Comedy"
echo "   • Action-Thriller"
echo "   • Adventure"
echo "   • Animation"
echo "   • Avant-Garde"
echo "   • Biographical Documentary"
echo "   • Biographical Drama (Biopic)"
echo "   • Comedy"
echo "   • Coming-of-Age"
echo "   • Crime Drama"
echo "   • Crime Thriller"
echo "   • Dramedy"
echo "   • Documentary"
echo "   • Docudrama"
echo "   • Essay Film"
echo "   • Experimental Documentary"
echo "   • Family / Kids"
echo "   • Fantasy"
echo "   • Fantasy Adventure"
echo "   • Historical Drama"
echo "   • Historical Fiction"
echo "   • Horror"
echo "   • Hybrid Experimental"
echo "   • Meta-Cinema"
echo "   • Mockumentary"
echo "   • Musical"
echo "   • Musical Drama"
echo "   • Mystery Thriller"
echo "   • Noir / Neo-Noir"
echo "   • Parody / Spoof"
echo "   • Performance Film"
echo "   • Period Piece"
echo "   • Political Drama"
echo "   • Political Thriller"
echo "   • Psychological Thriller"
echo "   • Reality-Drama"
echo "   • Romance"
echo "   • Romantic Comedy (Rom-Com)"
echo "   • Romantic Drama"
echo "   • Satire"
echo "   • Science Fiction (Sci-Fi)"
echo "   • Sci-Fi Horror"
echo "   • Slow Cinema"
echo "   • Sports Drama"
echo "   • Superhero"
echo "   • Surrealist"
echo "   • Thriller"
echo "   • True Crime"
echo "   • Visual Poetry"
echo "   • War"
echo "   • Western"
echo ""
echo "✅ Genre dropdown update completed!"
echo "🎯 The dropdown now uses FALLBACK_GENRES instead of hardcoded basic genres"