apiVersion: gitops/v1
kind: Application
metadata:
  name: pitchey-staging
  environment: staging
  labels:
    app: pitchey
    tier: staging
    component: full-stack
  annotations:
    gitops.io/last-applied: ""
    gitops.io/sync-policy: "automated"
    gitops.io/health-check: "enabled"
spec:
  source:
    repoURL: https://github.com/your-org/pitchey
    path: "."
    targetRevision: staging
  destination:
    platform: cloudflare
    account: e16d3bf549153de23459a6c6a06a431b
  
  # Worker configuration
  worker:
    name: pitchey-staging
    script: src/worker-production-db.ts
    compatibility_date: "2024-11-01"
    compatibility_flags: ["nodejs_compat"]
    
    # Environment variables (non-sensitive)
    env_vars:
      ENVIRONMENT: staging
      FRONTEND_URL: https://pitchey-staging.pages.dev
    
    # Resource limits (lower than production)
    resources:
      memory: 128MB
      cpu_time: 50ms
      
    # Bindings
    bindings:
      kv_namespaces:
        - binding: KV
          id: staging-kv-namespace-id  # Different from production
      
      r2_buckets:
        - binding: R2_BUCKET
          bucket_name: pitchey-uploads-staging
      
      durable_objects:
        - name: WEBSOCKET_ROOM
          class_name: WebSocketRoom
        - name: NOTIFICATION_ROOM
          class_name: NotificationRoom
    
    # Routes
    routes:
      - pattern: "pitchey-staging.cavelltheleaddev.workers.dev/*"
        zone_id: ""
  
  # Pages configuration
  pages:
    project: pitchey-staging
    production_branch: staging
    build_config:
      build_command: "cd frontend && npm ci && npm run build"
      destination_dir: "frontend/dist"
      root_dir: "."
      
    # Custom domains
    custom_domains:
      - domain: pitchey-staging.pages.dev
        ssl: flexible
  
  # Domain configuration
  domain: pitchey-staging.pages.dev
  
  # Monitoring and health checks (less frequent than production)
  monitoring:
    health_checks:
      - name: api-health
        url: https://pitchey-staging.cavelltheleaddev.workers.dev/api/health
        interval: 120s
        timeout: 10s
        retries: 2
      
      - name: frontend-health
        url: https://pitchey-staging.pages.dev
        interval: 300s
        timeout: 15s
        retries: 2
    
    alerts:
      - name: worker-down
        condition: health_check_failed
        target: api-health
        notifications: []
  
  # Sync policy (more aggressive than production)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 3
      backoff:
        duration: 2s
        factor: 2
        maxDuration: 1m
  
  # Rollback configuration
  rollback:
    strategy: immediate
    health_check_grace_period: 30s
    auto_rollback_on_failure: true
    preserve_previous_version: false  # Don't preserve in staging
    max_rollback_revisions: 3
  
  # Security settings (relaxed for testing)
  security:
    content_security_policy: false
    rate_limiting: false
    ddos_protection: false
    
  # Performance settings (less aggressive caching)
  performance:
    cache_ttl: 300  # 5 minutes
    compression: true
    minification: false  # Easier debugging
    image_optimization: false