# GitHub Environment Configuration for Staging
# This file documents the required environment configuration
# Actual setup is done through GitHub UI: Settings > Environments

environment_name: staging

# Protection rules (configure in GitHub UI)
protection_rules:
  required_reviewers: 0
  prevent_self_review: false
  dismiss_stale_reviews: true

# Deployment restrictions
deployment_branches:
  - main
  - develop
  - feature/*

# Required secrets (configure in GitHub UI)
required_secrets:
  # Cloudflare configuration
  - CLOUDFLARE_API_TOKEN
  - CLOUDFLARE_ACCOUNT_ID
  
  # Staging-specific secrets
  - STAGING_KV_NAMESPACE_ID
  - STAGING_HYPERDRIVE_ID
  - STAGING_DATABASE_URL

  # Third-party services
  - STAGING_SENTRY_DSN
  - STAGING_SENTRY_AUTH_TOKEN
  - STAGING_UPSTASH_REDIS_REST_URL
  - STAGING_UPSTASH_REDIS_REST_TOKEN

# Required variables (configure in GitHub UI)
required_variables:
  - ENVIRONMENT_NAME: staging
  - API_URL: https://pitchey-staging.ndlovucavelle.workers.dev
  - FRONTEND_URL: https://pitchey-staging.pages.dev
  - ALLOWED_ORIGINS: https://pitchey-staging.pages.dev
  - LOG_LEVEL: debug
  - RATE_LIMIT_ENABLED: true
  - RATE_LIMIT_MAX_REQUESTS: 1000
  - CACHE_TTL: 300
  - SESSION_TIMEOUT: 3600
  - MAX_FILE_SIZE: 10485760
  - ENABLE_ANALYTICS: true
  - ENABLE_MONITORING: true

# Auto-deployment configuration
auto_deployment:
  enabled: true
  branches:
    - main
  paths_ignored:
    - "*.md"
    - "docs/**"
    - ".gitignore"

# Monitoring and alerting
monitoring:
  health_check_url: https://pitchey-staging.ndlovucavelle.workers.dev/health
  uptime_check_interval: 300 # 5 minutes
  alert_channels:
    - slack
    - email

# Performance thresholds
performance_thresholds:
  response_time_p95: 2000 # milliseconds
  error_rate_threshold: 5 # percentage
  availability_threshold: 99.0 # percentage

# Security configuration
security:
  dependency_scanning: true
  secret_scanning: true
  code_scanning: true
  vulnerability_alerts: true

# Backup configuration
backup:
  database_backup_frequency: daily
  retention_period: 30 # days
  backup_storage: staging-backups

# Feature flags for staging
feature_flags:
  enable_beta_features: true
  enable_debug_logging: true
  enable_performance_monitoring: true
  enable_error_tracking: true
  skip_email_verification: true
  mock_payment_processing: true